### ISSUE TITLE
Add GitHub Actions

### ISSUE THREAD

**Issue by mchernigin** [MergeMinds/mm-frontend#4]
I think, we should add CI to check if project builds and code is formatted correctly.

[Not sure which tags I should add here]

**Comment by tolstovr** [comment]
Добавил метку ci/cd.

Да, было бы неплохо это реализовать. Но я таким ещё ни разу не занимался, так что не эксперт :)

**Comment by mchernigin** [comment]
Do you want to try it tho? I can help out as I have experience with GitHub Actions in general.

**Comment by mchernigin** [comment]
> Added `ci/cd` label.
> 
> Yes, it would be great to do this, but I have no experience with that:)


Do you want to try it tho? I can help out as I have experience with GitHub Actions in general.

**Comment by tolstovr** [comment]
I mean why not :)
We should discuss about this ig
