### ISSUE TITLE
Should we store yarn.lock in the repo?

### ISSUE THREAD

**Issue by mchernigin** [MergeMinds/mm-frontend#5]
The problem is that I usually prefer to use bun rn, so it creates `bun.lockb` and ignores `yarn.lock`. So the question is Should we
- remove lockfile from the repo and don't even bother
- all use `yarn` or agree on any other particular tool
- have all of the lock files in the repo

**Comment by tolstovr** [comment]
По-моему в `yarn.lock` содержатся фиксированные версии зависимостей, что важно в долгосрочной перспективе. Всё-таки, мне кажется, что лучше либо использовать один инструмент, либо хранить несколько lockfile-ов

**Comment by mchernigin** [comment]
Ok, let's stick with yarn then.
